### ISSUE TITLE
Is it possible to get more than 8 recording slots in the future?

### ISSUE THREAD

**Issue by Shodokan** [Grouflon/3rd_training_lua#11]
There are a few situations that would be worth having more slots.  Like practicing spacing/neutral against the randomized repeat option.

While 8 is quite a bit for most situations sometimes having 4-8 more could be very helpful with practicing situations with more than 8 options.  Specifically where having slight timing variance isn't supported by just adding extra frames before beginning or after ending(since the variance might be in the middle of the actions and you'd manually have to set them).  The best example of this is neutral due to the amount of walking one might do forward or backwards before making choices.  So while 8 may be enough to practice a few at once being able to encompass more options into the same set allows for a more realistic experience.

Also not now since there are many things that need fixing/adding first but eventually it might be nice to be able to add weighting to the replay functionality.  So its psuedo random since there are also situations where specific options are more likely to occur but others may also occur at less frequency.

**Comment by Shodokan** [comment]
Edit:

I found how to edit this and it was very well coded to the point where nothing was working incorrectly with some tweaks.  This is wonderful.  I can now manually weight for now.

**Comment by Grouflon** [comment]
Yes, as you saw the number of recordings is just a number to change in the script. Technically there could be hundreds of slots, but I think it's good to keep it to a manageable size. Maybe something like 16 would be good.
I think adding weights to the slots should not be very complicated as well, I'll add that to the roadmap

**Comment by Shodokan** [comment]
You might not have to, they may push a version on here for you that has it completed.  Said it may be done today.

**Comment by Shodokan** [comment]
That was now added in the pull request.  Hopefully you can add it to the master with the next update.
