### ISSUE TITLE
Suggestion: Option to have p1 auto block (or hold down back) during recordings

### ISSUE THREAD

**Issue by Shodokan** [Grouflon/3rd_training_lua#14]
But not record p1 inputs so the block isn't recorded.

Its very important for some frame trap setups and for practicing things like defending necro pressure due to some of his moves recovering at different times when blocked.

**Comment by Grouflon** [comment]
What I would like, would be to have P1 behave as the dummy you've set in the menu when you are recording.
This is unfortunately not feasable with the current input swap implementation, but will probably be easy to do in the next Fightcade's FBNeo version.

**Comment by Grouflon** [comment]
The P1 should now behave as the dummy when you are recording or pre-recording. Can you test and confirm me that this solves your issue ?
