### ISSUE TITLE
Error: Failed to save training settings to training settings.json

### ISSUE THREAD

**Issue by supersosko** [Grouflon/3rd_training_lua#19]
I'm using the most recent version of FBNeo packaged in fightcade 2. The trainer is working idk why that error is appearing

**Comment by Grouflon** [comment]
It seems that the permissions given to the lua scripts have changed compared to FBA-rr's implementation and that the script can no longer create files.
I'll be investigating that, but meanwhile you can just create the file training_settings.json yourself inside the saved directory and it should work

**Comment by Grouflon** [comment]
Well, I ran more tests and the behavior is super inconsistent. At first no write operations were working, even if I created the file, but at some point, after letting the script run for some time, it started to work again.
I believe there is a bug in the lua implementation, I'm currently in contact with fightcade's FBNeo fork developers to see if they can address it.

**Comment by Grouflon** [comment]
I contacted one of Fightcade's developers, and this bug should be fixed with the next version of Fightcade

**Comment by supersosko** [comment]
Dude awesome!

**Comment by Grouflon** [comment]
The last version is out, it should be fixed with the last version of fightcade. Can you test on your side and confirm me that it's gone ?
