### ISSUE TITLE
Counter attack action interactions with Load State

### ISSUE THREAD

**Issue by rsnoob35** [Grouflon/3rd_training_lua#2]
If the dummy is in hitstun or blockstun and then a savestate is loaded, the dummy will still do a move after the state is loaded. If the state was loaded during hitstun, the move will either happen immediately upon load or after about half a second. If the state was loaded during blockstun, the move will either happen after half a second or not at all.

The most consistent way to get the dummy to act immediately upon load state is to do short short super and load state during super flash

**Comment by Grouflon** [comment]
Thanks, I would not have caught that one by myself.
I think this should be fixed on the dev branch

**Comment by rsnoob35** [comment]
It's fixed as far as I can tell, nice. You're awesome for making this by the way, it's already one of the best training modes you can get if you play on PC

Random aside, I found this a while ago and wanted to make sure you were aware of it; it's ESN's spreadsheet of in-game addresses, figured it might save you some time if you were finding them yourself https://docs.google.com/spreadsheets/d/1eLi9phXMj18QGLfugrHhEQEjIVvSI2zbbUmDgPuLSf0/edit#gid=706955060

**Comment by Grouflon** [comment]
Wow, I wasn't aware of this. This would have saved me so much time haha T.T
Thank you very much !
