### ISSUE TITLE
Allow replays to begin before the training dummy is actionable

### ISSUE THREAD

**Issue by rsnoob35** [Grouflon/3rd_training_lua#3]
There are certain option selects that can only be done by holding directions/doing motions before your character is actionable. Guard jumping is the most important example of this, but can also apply to things such as delayed DP/super out of block. Adding this would also allow you to add command inputs like DP/super to the replay slots, which would let you practice doing things like microblock >throw on your enemy's wakeup

10 frames before being actionable should be plenty of time to do most commands if they're entered frame by frame

**Comment by Grouflon** [comment]
I think that's a great idea, but I'm not sure about manually entering the commands frame by frame. I can't really figure out a way of making it practical in terms of user interface...
What do you think about just setting up a number of offset frames for each slot into the recording settings pannel ?

**Comment by rsnoob35** [comment]
Entering replays frame by frame is already plenty doable if you use the emulator's pause and frame advance functions

I think an offset for each slot would work well, it'd address this issue and be a nice alternative way to make the dummy block for a specific amount of time before starting a replay

**Comment by Grouflon** [comment]
I'll go for the offset for now. I really like the fact that you can use every feature of the training mode with a regular controller and I would rather not compromize on this if possible.
I would be curious about your feedback on it as a user though. I'll keep you aware of when I find the time to implement it.

**Comment by rsnoob35** [comment]
Speaking of the Offset replay start feature, would it be hard to allow the user to randomize the delay between two arbitrary values? You could use this to practice reacting to whatever you set the replay as, either by whiff punishing, reversaling, anti airing, or whatever else you can think of

**Comment by Grouflon** [comment]
What I have in mind is being able save recorded sequence from a slot to individual files, and then being able to reload them at any time to any slot.
With that, you could load your sequence into different slots, put a different delay in each slot, and then use the regular randomized replay to achieve what you want, without having to add a specific randomizing feature. This seems more powerful to me

**Comment by rsnoob35** [comment]
I would say that's good, but what would I do if I wanted to practice reacting to more than one option? That would cut the 8 timing variations in half at least. If you feel like other features are more important to prioritize I'd definitely agree, but I still think there's merit for an individual random delay for each slot, or at least a global randomized delay for all the different replays.

**Comment by rsnoob35** [comment]
Works great in the new version!
