### ISSUE TITLE
[bug] the menu does not appear

### ISSUE THREAD

**Issue by guildsnake** [Grouflon/3rd_training_lua#36]
when I press start the menu does not appear
when I paste in the softfx the inputs are in the wrong place and in the basic or enchanced they do not appear (the menu does not appear in either)  the example in the photo is in the softfx
![20210303_160736](https://user-images.githubusercontent.com/80000618/109858442-971ade80-7c3a-11eb-80d1-5d6484470558.jpg)

**Comment by Grouflon** [comment]
Hello !
This looks like a common problem when you are not using the correct blitter options.
Try to set the blitter to default

**Comment by guildsnake** [comment]
the problem is, i dont no why, the direct x9 alt and experimental not works, but thanks!

**Comment by Grouflon** [comment]
Maybe try asking for help directly on the fightcade discord. This looks more related to the emulator+your config than to the script
