### ISSUE TITLE
Issue & Suggestions

### ISSUE THREAD

**Issue by Shodokan** [Grouflon/3rd_training_lua#4]
First off thank you for trying to create a better alternative for training mode/practice for 3s... it honestly is a game that needs it. 

---Issue---
If i press anything other than LK (I pressed LP) while in training menu(that is not recording screen) all actions in the game will lock up until i re-load the LUA, so it will not allow me to do anything with either player's buttons but sound and such will still play (it gave an LUA error as well).  The only time LP didn't cause this for me is on the recording portion when it is meant to remove/clear a recorded action on its specific screen.

---Suggestions---
There should be a geneijin/seienbu mode for meter (if possible) that will allow you to see the meter depletion since full meter will not show this as this is an integral part of using these supers properly.  This may be possible by simply adding a feature to let you use the LUA CUSTOM HOTKEY built into the EMU to set player 1/2 meter to maximum as the user sees fit.   I honestly think using the LUA CUSTOM HOTKEY as a way to max or remove all meter would be very useful in general.

To take the above a step further I think the best way to implement it is to allow the user to set the amount of meter that it is set to with said LUA CUSTOM HOTKEY.  This would allow players to create and practice DED scenarios (like where ken's c mk will super if the opponent is hit but will not if they block).  You may also be able to add in the functionality of "Before replay use set meter" to make practicing these situations a bit easier without save states.

You could also eventually add special block/random action section that auto randomizes between blocking, jumping, hitting d+lp/throw and throwing while holding back.  This would be useful for practicing confirming in geneijin without having to manually create 8+ scenarios, can also possibly add a "ms before next randomized action" for this (it should always start blocking).  Alternatively I can use the other macro creation LUA to create a set of 20-30 patterns you can use as its randomized choices.

Another suggestion is to add some functionality between loading a saved state as well as starting the recorded sequence playing without needing to use a macro of some kind to make one button do multiple things using external programs such as X-Padder along with other software for macros.  Currently I need to use AutoHotKey to create a macro that uses the load state button and then it will hit the button that is used to play recording  twice in case all of the frames had not completed playing to cancel and re-start it. (I don't know if this is possible with LUA scripting)

The other issue brought up i will echo as well that being able to program pre-determined actions such as guard jump more easily (like the very start of the replay) without needing to worry about inputting it frame by frame can be extremely useful.  Alternatively you can just include a guide on how to do this in the read-me.  

Adding an option for advanced users such as "Record with frame zero pause" so you can manually set inputs frame by frame would be VERY helpful and take some of the frustration out of getting the pause on the first frame in its current state.  This will make things like programming random parry after resets possible, but could also be added as a base functionality (such as akuma lk tatsu > s lp > SA1 or dudley jump X > land > duck SA3.... or geneijin resets) where if the opponent has been hit but can still parry due to the reset it chooses to parry the first hit that connects with it randomly.

One last thing is possibly adding in the ability to toggle the hidden bar portion of the other training mode LUA that NICA K.O showcased/distributed that has the lightning leg, charge partition, ability to parry etc etc. (as seen here-   https://www.youtube.com/watch?v=ogefVDZGPY0)

Another thing is that because guard jump is a thing it might be a good idea to add in a way for us to change the amount of frames before counter attack occurs.  So its not always frame 0-1, especially because with this you can put realistic guard jump as an option since it takes 3 frames of blocking before it can jump after a knockdown situation.  This also helps with making more realistic situations and encompass varied timing of their choices.

**Comment by rsnoob35** [comment]
> Adding an option for advanced users such as "Record with frame zero pause" so you can manually set inputs frame by frame would be VERY helpful and take some of the frustration out of getting the pause on the first frame in its current state.

You can do this in it's current state by enabling the "Auto crop first frames" option under Recording Settings; are there situations where that doesn't cut it? I agree though, I don't think there should be a delay after pressing P2 coin to start/end the replay if there doesn't need to be. Whatever you could accomplish with that could also be accomplished with Auto crop first frames and the Offset replay start" feature Grouflan was talking about implementing.

**Comment by Jaxsaon** [comment]
A delay (about 3 to 6 seconds) between the end of a combo and the refill of the health

**Comment by Grouflon** [comment]
> 
> 
> A delay (about 3 to 6 seconds) between the end of a combo and the refill of the health

Yes, that is something I plan to do. I'm not sure if I should make it a specific mode, or juste replace the infinite life mode though

**Comment by Jaxsaon** [comment]
Id say replace the infinite life with the delay

**Comment by Jaxsaon** [comment]
> > A delay (about 3 to 6 seconds) between the end of a combo and the refill of the health
> 
> Yes, that is something I plan to do. I'm not sure if I should make it a specific mode, or juste replace the infinite life mode though

Great work! Keep it up! Never thought about the idle animation for the refill(although id put 60 instead of 20)! 
One last thing that'd be really nice is implementing two "scores": one for the health and one for the super, so for the diehard combo optiming fans theres a great tool to help them optiming combos

**Comment by Grouflon** [comment]
I think I'll juste expose the values when you set the mode to refill, that will allow everyone to set the value to their liking

**Comment by bola385** [comment]
Two things that I noticed, that I'm sure other people saw as well, is that the "repeat random" recording option is not working, also, when you're recording, it looks like you can't access your EX Moves. From what I saw, that's pretty much it. Thank you for the awesome work!!

**Comment by rsnoob35** [comment]
Idea: On-screen feedback for parry training. If a parry attempt is detected within, say, 10 frames before or after the parry window for a move starts or ends, a popup would tell you exactly how early/late you were. If you landed the parry, it would tell you what frame of the parry window the move connected on (for example, 1/5 would come up if your parry came out on the same frame a jump in attack connected). This would help newer players get the timing down for regular parries and help more advanced players practice red parries.

**Comment by Grouflon** [comment]
This issue is becoming quite difficult to manage for me, would it be possible for you guys to re-evaluate each of your requests (I may have already adressed it), and open a different issue for each one that is still valid ? That would help a lot
