### ISSUE TITLE
[Bug] Dummy not affected by Infinite Meter 

### ISSUE THREAD

**Issue by rsnoob35** [Grouflon/3rd_training_lua#6]

**Comment by Shodokan** [comment]
If you save state before the infinite meter is active it will not show it is there even when active. For good measure turn on and off the meter a few times.  If you control the dummy after that and hit at all your meter jumps to full.  Its an issue with other "full meter" things as well where the meter is set to full but the game will not show it for whatever reason.  Or simply turn the meter on and then make your savestate.

I thought it was the same when doing makoto post hayate mixup recording where it didn't have meter and went for EX oroshi. I turned on and off the infinite meter and it worked.  After that i tried it again from a fresh launch of the emu + LUA and it did not have the issue even making a new savestate before the meter was set to full again.

**Comment by rsnoob35** [comment]
This is a v0.4 exclusive bug, I'm 99% sure it worked properly in 0.3

**Comment by Grouflon** [comment]
Okay, thanks that's interesting, I changed tiny things about meter between the two. I'll definitely check that.
Meter management is quite difficult to pin down, it does not work like life or stun, where you just set a value in memory and the bar gets updated accordingly. Meter seems stored in different locations, and also to only update the visual bar when some game events occur...

**Comment by Grouflon** [comment]
This should be fixed on the dev branch, and join the main branch with version 0.5
