### ISSUE TITLE
[0.6 Master] Cannot link moves into super

### ISSUE THREAD

**Issue by rsnoob35** [Grouflon/3rd_training_lua#8]
Tested as Dudley, Ken, Sean, Q. Cancels into super still work properly.

**Comment by Shodokan** [comment]
Also experiencing this as well as more outlined in my other thread.

**Comment by Grouflon** [comment]
you mean while recording or in general ?

**Comment by rsnoob35** [comment]
In general. I couldn't get f.mk > super, st.mp xx ducking super, or overhead > super to register as combos even if I did them in frame advance mode

**Comment by Grouflon** [comment]
That's pretty weird. On the top of my head I can't really see why the script would cause this behavior since it's not supposed to affect the player's input in normal mode. I should investigate to see which part of the script is causing the issue.

**Comment by OscarCapac** [comment]
I have found that the following block that write at the recovery time address was causing the bug.
https://github.com/Grouflon/3rd_training_lua/blob/1caeb0fb15a66b5589a40d8dc61b320951e1cb15/3rd_training.lua#L2479-L2482
Commentating it resolve the bug.

**Comment by Grouflon** [comment]
You're right, I commited your fix on the dev branch, it should go on master with the next update
